language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.1
install:
  - "pip install --use-mirrors Django==$DJANGO_VERSION"
  - "pip install --use-mirrors django-jenkins pylint coverage"
  - "pip install --use-mirrors --editable ."
script: "django-admin.py jenkins --settings=flows.tests.settings flows"
